# Generated by Django 4.0.4 on 2022-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='about_img')),
                ('libele', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='blog_img')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPlat', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('description', models.TextField()),
                ('date_update', models.DateTimeField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatFavorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='plat_img')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
