# Generated by Django 4.0.4 on 2022-05-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_rename_image_about_image_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='image_blog',
        ),
    ]
