# Generated by Django 4.0.4 on 2022-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='banner_imgs')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reseau_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sectionImageblock', models.FileField(upload_to='site_imgs')),
                ('sectionBlockLibele', models.CharField(max_length=100)),
                ('menuDescription', models.TextField()),
                ('sectionNewsLetter', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sectionDescription', models.TextField()),
                ('sectionCopyright', models.CharField(max_length=50)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
