# Generated by Django 4.0.4 on 2022-05-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='sectionBlockLibele',
            new_name='sectionBlockLabele',
        ),
    ]
