# Generated by Django 4.0.4 on 2022-05-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_rename_sectionblocklibele_site_sectionblocklabele'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='image_banners',
        ),
    ]
